<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(NETCoreTargetFramework)</TargetFramework>
    <Shipping>true</Shipping>
    <PackProject>true</PackProject>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <Description>NuGet localization package for dotnet CLI.</Description>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <UsePublicApiAnalyzer>false</UsePublicApiAnalyzer>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(OutputPath)**\NuGet.*.resources.dll"
          Pack="true"
          PackagePath="lib\$(TargetFramework)\" />
  </ItemGroup>

  <Target Name="SetProjectReferencesForBuild" BeforeTargets="PrepareForBuild">
    <ItemGroup>
      <ProjectReference Include="@(CoreProjects)"
                        Exclude="$(RepositoryRootDirectory)src\NuGet.Core\NuGet.Build.Tasks.Pack\NuGet.Build.Tasks.Pack.csproj;
                                 $(RepositoryRootDirectory)src\NuGet.Core\Microsoft.Build.NuGetSdkResolver\Microsoft.Build.NuGetSdkResolver.csproj;
                                 $(RepositoryRootDirectory)src\NuGet.Core\NuGet.Packaging.Core\NuGet.Packaging.Core.csproj" />
    </ItemGroup>
  </Target>
</Project>
