<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(TargetFrameworksLibrary)</TargetFrameworks>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <AssemblyName>NuGet.Build.Tasks.Pack</AssemblyName>
    <RootNamespace>$(AssemblyName)</RootNamespace>
    <Shipping>true</Shipping>
    <PackProject>true</PackProject>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <XPLATProject>true</XPLATProject>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);CreatePackNupkg</TargetsForTfmSpecificContentInPackage>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <DevelopmentDependency>true</DevelopmentDependency>
    <Description>NuGet tasks for MSBuild and dotnet pack.</Description>
    <NoWarn>$(NoWarn);NU5100</NoWarn>
    <DepsFileGenerationMode>old</DepsFileGenerationMode>
    <UsePublicApiAnalyzer>false</UsePublicApiAnalyzer>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <SkipILMerge Condition="'$(SkipILMerge)' == '' And ('$(TargetFramework)' == '' Or '$(BuildingInsideVisualStudio)' == 'true' Or '$(DotNetBuildSourceOnly)' == 'true')">true</SkipILMerge>
    <ILMergeAfterTargets Condition="'$(SkipILMerge)' != 'true'">Build</ILMergeAfterTargets>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\NuGet.Build.Tasks\Common\MSBuildLogger.cs" />
    <Compile Include="..\NuGet.Build.Tasks\GetProjectTargetFrameworksTask.cs" />
    <Content Include="NuGet.Build.Tasks.Pack.targets" Pack="true" PackagePath="build;buildCrossTargeting">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NuGet.Commands\NuGet.Commands.csproj" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == '$(NETFXTargetFramework)' ">
    <Reference Include="Microsoft.Build.Utilities.v4.0" Pack="false" />
    <Reference Include="Microsoft.Build.Framework" Pack="false" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ILMerge" PrivateAssets="All" Condition=" '$(DotNetBuildSourceOnly)' != 'true' " />
    <None Include="$(BuildCommonDirectory)NOTICES.txt" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' != '$(NETFXTargetFramework)' ">
    <PackageReference Include="Microsoft.Build.Framework" ExcludeAssets="runtime" GeneratePathProperty="true" />
    <PackageReference Include="Microsoft.Build.Tasks.Core" ExcludeAssets="runtime" GeneratePathProperty="true" />
    <PackageReference Include="Microsoft.Build.Utilities.Core" ExcludeAssets="runtime" GeneratePathProperty="true" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Strings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Strings.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Strings.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Strings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>


  <Target Name="ILMerge"
          AfterTargets="$(ILMergeAfterTargets)"
          DependsOnTargets="ILMergePackAssembly;ILMergeResourceAssemblies" />

  <Target Name="DetermineILMergeInputsOutputs">
    <ItemGroup>
      <BuiltNuGetPack Include="$(TargetPath)" />
      <ILMergedNuGetPack Include="$(OutputPath)ilmerge\$(TargetFileName)" />
      <BuildArtifacts Include="$(OutputPath)*.dll"
                      Exclude="%(BuiltNuGetPack.Identity)" />
    </ItemGroup>
    <Message Text="$(MSBuildProjectName) -&gt; @(ILMergedNuGetPack)" Importance="High" />
  </Target>

  <Target Name="ILMergePackAssembly"
          DependsOnTargets="DetermineILMergeInputsOutputs"
          Inputs="$(MSBuildAllProjects);@(BuiltNuGetPack);@(BuildArtifacts)"
          Outputs="@(ILMergedNuGetPack)">
    <PropertyGroup>
      <ILMergeLogFilePath>$(IntermediateOutputPath)ILMerge.log</ILMergeLogFilePath>
    </PropertyGroup>

    <MakeDir Directories="%(ILMergedNuGetPack.RootDir)%(ILMergedNuGetPack.Directory)" />

    <Delete Files="$(ILMergeLogFilePath)"
            Condition="Exists('$(ILMergeLogFilePath)')" />

    <ItemGroup>
      <ILMergeCommand Include="$(ILMergeConsolePath)" />
      <ILMergeCommand Include="/out:%(ILMergedNuGetPack.Identity)" />
      <ILMergeCommand Include="/allowDup" />
      <ILMergeCommand Include="/lib:$(OutputPath)" />
      <ILMergeCommand Include="/lib:$(PkgMicrosoft_Build_Utilities_Core)\lib\netstandard2.0" Condition=" '$(TargetFramework)' != '$(NETFXTargetFramework)' " />
      <ILMergeCommand Include="/lib:$(PkgMicrosoft_Build_Tasks_Core)\lib\netstandard2.0" Condition=" '$(TargetFramework)' != '$(NETFXTargetFramework)' " />
      <ILMergeCommand Include="/lib:$(PkgMicrosoft_Build_Framework)\lib\netstandard2.0" Condition=" '$(TargetFramework)' != '$(NETFXTargetFramework)' " />
      <ILMergeCommand Include="/internalize" />
      <ILMergeCommand Include="/log:$(ILMergeLogFilePath)" />
      <ILMergeCommand Include="/delaysign" Condition="'$(SkipSigning)' != 'true' And Exists($(AssemblyOriginatorKeyFile))" />
      <ILMergeCommand Include="/keyfile:$(AssemblyOriginatorKeyFile)" Condition="'$(SkipSigning)' != 'true' And Exists($(AssemblyOriginatorKeyFile))" />
      <ILMergeCommand Include="%(BuiltNuGetPack.Identity)" />
      <ILMergeCommand Include="%(BuildArtifacts.Identity)" />
    </ItemGroup>

    <Exec Command="@(ILMergeCommand->'%(Identity)', ' ')"
          IgnoreExitCode="true">
      <Output TaskParameter="ExitCode" PropertyName="ILMergeExitCode" />
    </Exec>

    <ItemGroup>
      <EmbedInBinlog Include="$(ILMergeLogFilePath)" />
    </ItemGroup>

    <Error Text="ILMerge.exe failed, see the log file '$(ILMergeLogFilePath)' for more information."
           Code="ILMERGE$(ILMergeExitCode)"
           Condition="'$(ILMergeExitCode)' != '0'" />
  </Target>

  <Target Name="ILMergeResourceAssemblies">
    <ItemGroup>
      <ResourceAssemblies Include="$(OutputPath)**\$(AssemblyName).resources.dll" Exclude="$(OutputPath)ilmerge\**" />
      <ProjectsToBuild Include="$(MSBuildProjectFullPath)" AdditionalProperties="CurrentCulture=%(ResourceAssemblies.RecursiveDir);BuildProjectReferences=false" />
    </ItemGroup>
    <MSBuild Projects="@(ProjectsToBuild)"
             BuildInParallel="true"
             Targets="ILMergeResourceAssembly" />
  </Target>

  <Target Name="DetermineILMergeResourceAssemblyInputsOutputs"
          DependsOnTargets="ResolveProjectReferences">
    <PropertyGroup>
      <PathToBuiltNuGetPackResource>$(OutputPath)$(CurrentCulture)NuGet.Build.Tasks.Pack.resources.dll</PathToBuiltNuGetPackResource>
      <PathToMergedNuGetPackResource>$(OutputPath)ilmerge\$(CurrentCulture)NuGet.Build.Tasks.Pack.resources.dll</PathToMergedNuGetPackResource>
    </PropertyGroup>
    <ItemGroup>
      <ResourceArtifacts Include="%(_ResolvedProjectReferencePaths.RootDir)%(_ResolvedProjectReferencePaths.Directory)$(CurrentCulture)NuGet*.resources.dll" />
    </ItemGroup>
    <Message Text="$(MSBuildProjectName) -&gt; $(PathToMergedNuGetPackResource)" Importance="High" />
  </Target>

  <Target Name="ILMergeResourceAssembly"
          DependsOnTargets="DetermineILMergeResourceAssemblyInputsOutputs"
          Inputs="$(MSBuildAllProjects);$(PathToBuiltNuGetPackResource);@(ResourceArtifacts)"
          Outputs="$(PathToMergedNuGetPackResource)"
          Condition="'$(TargetFramework)' != '' And '$(CurrentCulture)' != ''">
    <PropertyGroup>
      <ILMergeLogFilePath>$(IntermediateOutputPath)ilmerge\$(CurrentCulture)ilmerge.log</ILMergeLogFilePath>
    </PropertyGroup>

    <MakeDir Directories="$([System.IO.Path]::GetDirectoryName($(PathToMergedNuGetPackResource)))" />

    <MakeDir Directories="$([System.IO.Path]::GetDirectoryName($(ILMergeLogFilePath)))" />

    <Delete Files="$(ILMergeLogFilePath)"
            Condition="Exists('$(ILMergeLogFilePath)')" />

    <ItemGroup>
      <ILMergeCommand Include="$(ILMergeConsolePath)" />
      <ILMergeCommand Include="/out:$(PathToMergedNuGetPackResource)" />
      <ILMergeCommand Include="/allowDup" />
      <ILMergeCommand Include="/lib:$(OutputPath)" />
      <ILMergeCommand Include="/internalize" />
      <ILMergeCommand Include="/log:$(ILMergeLogFilePath)" />
      <ILMergeCommand Include="/delaysign" Condition="'$(SkipSigning)' != 'true' And Exists($(AssemblyOriginatorKeyFile))" />
      <ILMergeCommand Include="/keyfile:$(AssemblyOriginatorKeyFile)" Condition="'$(SkipSigning)' != 'true' And Exists($(AssemblyOriginatorKeyFile))" />
      <ILMergeCommand Include="$(PathToBuiltNuGetPackResource)" />
      <ILMergeCommand Include="%(ResourceArtifacts.Identity)" />
    </ItemGroup>

    <Exec Command="@(ILMergeCommand->'%(Identity)', ' ')"
          IgnoreExitCode="true">
      <Output TaskParameter="ExitCode" PropertyName="ILMergeExitCode" />
    </Exec>

    <ItemGroup>
      <EmbedInBinlog Include="$(ILMergeLogFilePath)" />
    </ItemGroup>

    <Error Text="ILMerge.exe failed, see the log file '$(ILMergeLogFilePath)' for more information."
           Code="ILMERGE$(ILMergeExitCode)"
           Condition="'$(ILMergeExitCode)' != '0'" />
  </Target>

  <!--These targets help get all the DLLs that are packed in the nuspec to be sent for signing.-->
  <Target Name="GetILMergeBuildOutput" Returns="@(ILMergeBuildOutput)">
    <ItemGroup>
      <ILMergeBuildOutput Include="$(OutputPath)ilmerge\*.dll" KeepDuplicates="false" />
      <ILMergeBuildOutput Include="$(OutputPath)ilmerge\*.xml" KeepDuplicates="false" />
    </ItemGroup>
  </Target>

  <!--These targets help get all the DLLs that are packed in the nuspec to be sent for signing.-->
  <Target Name="GetIlmergeSymbolOutput" Returns="@(SymbolsToIndex)">
    <ItemGroup>
      <SymbolsToIndex Include="$(OutputPath)ilmerge\*.pdb" KeepDuplicates="false" />
    </ItemGroup>
  </Target>

  <Target Name="GetFinalBuildOutput" Returns="@(DllsToIndex)">
    <ItemGroup>
      <DllsToIndex Include="$(OutputPath)ilmerge\NuGet.Build.Tasks.Pack.dll"/>
    </ItemGroup>
  </Target>

  <Target Name="CreatePackNupkg">
    <PropertyGroup>
      <!-- Build from source can't use ILMerge and XPLat builds don't run the ILmerge targets. -->
      <ILMergeSubpath Condition="'$(DotNetBuildSourceOnly)' != 'true' and '$(IsXPlat)' != 'true'">ilmerge\</ILMergeSubpath>
      <PackagePathDir Condition="'$(TargetFramework)' == '$(NETFXTargetFramework)'">Desktop/</PackagePathDir>
      <PackagePathDir Condition="'$(TargetFramework)' == '$(NetStandardVersion)'">CoreCLR/</PackagePathDir>
    </PropertyGroup>
    <ItemGroup>
      <TfmSpecificPackageFile Include="$(OutputPath)\$(ILMergeSubpath)NuGet.Build.Tasks.Pack.dll" Condition="'$(DotNetBuildSourceOnly)' != 'true'">
        <PackagePath>$(PackagePathDir)</PackagePath>
      </TfmSpecificPackageFile>
      <TfmSpecificPackageFile Include="$(OutputPath)\$(ILMergeSubpath)**\NuGet*.resources.dll">
        <PackagePath>$(PackagePathDir)</PackagePath>
      </TfmSpecificPackageFile>
      <TfmSpecificPackageFile Include="$(OutputPath)\$(ILMergeSubpath)NuGet*.dll" Condition="'$(DotNetBuildSourceOnly)' == 'true'">
        <PackagePath>$(PackagePathDir)</PackagePath>
      </TfmSpecificPackageFile>
    </ItemGroup>
  </Target>

  <PropertyGroup>
    <SignTargetsForRealSigning Condition="'$(IsSymbolsBuild)' != 'true'">GetILMergeBuildOutput</SignTargetsForRealSigning>
    <SymbolTargetsToGetPdbs>GetIlmergeSymbolOutput;GetFinalBuildOutput</SymbolTargetsToGetPdbs>
    <GetSigningInputsDependsOn>GetSigningInputsCustom</GetSigningInputsDependsOn>
  </PropertyGroup>

  <Target Name="GetSigningInputsCustom"
          DependsOnTargets="GetTargetFrameworkSet"
          Returns="@(DllsToSign)" Condition=" '$(Shipping)' == 'true' And '$(IncludeAssemblyInVSIXContainer)' != 'false' ">
    <MSBuild
      Projects="$(MSBuildProjectFullPath)"
      Targets="GetFilesToSign"
      Properties="TargetFramework=%(ProjectTargetFrameworkEntries.Identity);BuildProjectReferences=false;">
      <Output
          TaskParameter="TargetOutputs"
          ItemName="DllsToSign" />
    </MSBuild>
  </Target>

  <Target Name="GetFilesToSign"
          Returns="@(FilesToSign)">
    <ItemGroup>
      <FilesToSign Include="$(OutputPath)ilmerge\*.dll"
                   StrongName="MsSharedLib72"
                   Authenticode="Microsoft400" />

      <FilesToSign Include="$(OutputPath)ilmerge\**\*.resources.dll"
                   StrongName="MsSharedLib72"
                   Authenticode="Microsoft400" />
    </ItemGroup>
  </Target>
</Project>
