<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="ilmerge.props" />

  <PropertyGroup>
    <TargetFramework>$(NETFXTargetFramework)</TargetFramework>
    <Description>NuGet Command Line Interface for repository signing.</Description>
    <Shipping>true</Shipping>
    <PackProject>false</PackProject>
    <IncludeInVsix>false</IncludeInVsix>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <GetSigningInputsDependsOn>GetSigningInputsCustom</GetSigningInputsDependsOn>
    <GetSymbolsToIndexDependsOn>GetSymbolsToIndexCustom</GetSymbolsToIndexDependsOn>
    <SignWithMicrosoftKey>true</SignWithMicrosoftKey>
    <SkipILMerge Condition="'$(SkipILMerge)' == '' And ('$(BuildingInsideVisualStudio)' == 'true' Or '$(DotNetBuildSourceOnly)' == 'true')">true</SkipILMerge>
    <ILMergeAfterTargets Condition="'$(SkipILMerge)' != 'true'">Build</ILMergeAfterTargets>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ILMerge" PrivateAssets="All" />
    <None Include="$(BuildCommonDirectory)NOTICES.txt" Pack="true" PackagePath="\" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\NuGet.CommandLine\NuGet.CommandLine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="NuGetMSSignCommand.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>NuGetMSSignCommand.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="NuGetMSSignCommand.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>NuGetMSSignCommand.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <Target Name="DetermineILMergeInputsOutputs">
    <PropertyGroup>
      <PathToBuiltNuGetExe>$(OutputPath)NuGet.exe</PathToBuiltNuGetExe>
      <PathToMergedNuGetExe>$(ArtifactsDirectory)$(VsixOutputDirName)\NuGet.Mssign.exe</PathToMergedNuGetExe>
    </PropertyGroup>
    <ItemGroup>
      <BuildArtifacts Include="$(OutputPath)\*.dll" Exclude="@(MergeExclude)" />
    </ItemGroup>
    <Message Text="$(MSBuildProjectName) -&gt; $(PathToMergedNuGetExe)" Importance="High" />
  </Target>

  <Target Name="ILMerge"
          AfterTargets="$(ILMergeAfterTargets)"
          DependsOnTargets="DetermineILMergeInputsOutputs"
          Inputs="$(MSBuildAllProjects);$(PathToBuiltNuGetExe);@(BuildArtifacts)"
          Outputs="$(PathToMergedNuGetExe)">
    <Error Text="Build dependencies are inconsistent with mergeinclude specified in ilmerge.props" Condition="'@(BuildArtifacts-&gt;Count())' != '@(MergeInclude-&gt;Count())'" />

    <PropertyGroup>
      <ILMergeLogFilePath>$(IntermediateOutputPath)ILMerge.log</ILMergeLogFilePath>
    </PropertyGroup>

    <MakeDir Directories="$([System.IO.Path]::GetDirectoryName($(PathToMergedNuGetExe)))" />

    <Delete Files="$(ILMergeLogFilePath)"
            Condition="Exists('$(ILMergeLogFilePath)')" />

    <ItemGroup>
      <ILMergeCommand Include="$(ILMergeConsolePath)" />
      <ILMergeCommand Include="$(PathToBuiltNuGetExe)" />
      <ILMergeCommand Include="/lib:$(OutputPath)" />
      <ILMergeCommand Include="/out:$(PathToMergedNuGetExe)" />
      <ILMergeCommand Include="/allowdup:%(MergeAllowDup.Identity)" />
      <ILMergeCommand Include="/log:$(ILMergeLogFilePath)" />
      <ILMergeCommand Include="/delaysign" Condition="'$(SkipSigning)' != 'true' And Exists($(AssemblyOriginatorKeyFile))" />
      <ILMergeCommand Include="/keyfile:$(AssemblyOriginatorKeyFile)" Condition="'$(SkipSigning)' != 'true' And Exists($(AssemblyOriginatorKeyFile))" />
      <ILMergeCommand Include="%(BuildArtifacts.FullPath)" />
    </ItemGroup>
    <!--<PropertyGroup>
      <ILMergeCommand>$(ILMergeConsolePath) $(PathToBuiltNuGetExe) /lib:$(OutputPath) @(BuildArtifacts->'%(filename)%(extension)', ' ') /out:$(PathToMergedNuGetExe) @(MergeAllowDup -> '/allowdup:%(Identity)', ' ')</ILMergeCommand>
      <ILMergeCommand Condition="'$(SkipSigning)' != 'true' And Exists($(AssemblyOriginatorKeyFile))">$(ILMergeCommand) /delaysign /keyfile:$(AssemblyOriginatorKeyFile)</ILMergeCommand>
    </PropertyGroup>-->
    <Exec Command="@(ILMergeCommand->'%(Identity)', ' ')"
          IgnoreExitCode="true">
      <Output TaskParameter="ExitCode" PropertyName="ILMergeExitCode" />
    </Exec>

    <ItemGroup>
      <EmbedInBinlog Include="$(ILMergeLogFilePath)" />
    </ItemGroup>

    <Error Text="ILMerge.exe failed, see the log file '$(ILMergeLogFilePath)' for more information."
           Code="ILMERGE$(ILMergeExitCode)"
           Condition="'$(ILMergeExitCode)' != '0'" />
  </Target>

  <Target Name="GetSigningInputsCustom" Returns="@(DllsToSign)">
    <ItemGroup>
      <DllsToSign Include="$(ArtifactsDirectory)$(VsixOutputDirName)\NuGet.Mssign.exe">
        <StrongName>MsSharedLib72</StrongName>
        <Authenticode>Microsoft400</Authenticode>
      </DllsToSign>
    </ItemGroup>
  </Target>

  <Target Name="GetSymbolsToIndexCustom" Returns="@(SymbolsToIndex)">
    <ItemGroup>
      <SymbolsToIndex Include="$(ArtifactsDirectory)$(VsixOutputDirName)\NuGet.Mssign.exe" />
      <SymbolsToIndex Include="$(ArtifactsDirectory)$(VsixOutputDirName)\NuGet.Mssign.pdb" />
    </ItemGroup>
  </Target>
</Project>
